Create liste.c
AlinaMi/Exercise pull request #3
Opened 2017-03-24 15:26 UTC by AlinaMi

Am mai facut ceva;)). Ceea ce inca nu mi-e clar e ca daca apelez functia temp_i = delete_first(head, val);  cu primul parametru egal cu noul head, isi pierde cred eu referinta si nu mai functioneaza ... o sa continui luni :) weekend placut!

2017-03-27 07:05 UTC, cristianene requested changes

2017-03-27 07:05 UTC, cristianene commented on liste.c
> +
Always check if malloc returns NULL

2017-03-27 07:05 UTC, cristianene commented on liste.c
> +Node* delete_first(Node* head, int val)
My suggestion is to create a function to delete the first occurence of a value in a list and then call it consecutively until all the nodes  with that values are deleted.

delete_first - delete the first occurence of val in the list
delete_node - delete all the occurences of val in the list by using the delete_first

2017-03-28 10:26 UTC, AlinaMi commented on liste.c
> +
if(new_node == NULL)
	{
		printf("Memory allocation failed.\n");
		return 0;
	}

2017-06-16 13:30 UTC, merged